import { format } from 'date-fns';

interface ExpenseData {
  id: string;
  description: string;
  amount: number;
  expense_date: string;
  expense_type: string;
  category?: string | null;
}

export function exportToCSV(expenses: ExpenseData[], filename: string = 'expenses') {
  const headers = ['Date', 'Description', 'Category', 'Type', 'Amount (₹)'];
  
  const rows = expenses.map(expense => [
    format(new Date(expense.expense_date), 'dd/MM/yyyy'),
    expense.description.replace(/,/g, ';'), // Escape commas
    expense.category || 'General',
    expense.expense_type,
    expense.amount.toFixed(2),
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(',')),
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}_${format(new Date(), 'yyyy-MM-dd')}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportToPDF(expenses: ExpenseData[], filename: string = 'expenses') {
  const total = expenses.reduce((sum, e) => sum + e.amount, 0);
  
  // Create printable HTML
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Expense Report</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        h1 { color: #10b981; margin-bottom: 5px; }
        .subtitle { color: #666; margin-bottom: 30px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #10b981; color: white; padding: 12px; text-align: left; }
        td { padding: 10px 12px; border-bottom: 1px solid #eee; }
        tr:nth-child(even) { background: #f9f9f9; }
        .total-row { background: #f0fdf4 !important; font-weight: bold; }
        .amount { text-align: right; }
        .category { 
          display: inline-block; 
          padding: 2px 8px; 
          background: #e5e7eb; 
          border-radius: 4px; 
          font-size: 12px;
        }
        .footer { margin-top: 30px; font-size: 12px; color: #999; }
      </style>
    </head>
    <body>
      <h1>Expense Report</h1>
      <p class="subtitle">Generated on ${format(new Date(), 'dd MMMM yyyy, hh:mm a')}</p>
      
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Description</th>
            <th>Category</th>
            <th>Type</th>
            <th class="amount">Amount</th>
          </tr>
        </thead>
        <tbody>
          ${expenses.map(expense => `
            <tr>
              <td>${format(new Date(expense.expense_date), 'dd MMM yyyy')}</td>
              <td>${expense.description}</td>
              <td><span class="category">${expense.category || 'General'}</span></td>
              <td>${expense.expense_type}</td>
              <td class="amount">₹${expense.amount.toLocaleString('en-IN')}</td>
            </tr>
          `).join('')}
          <tr class="total-row">
            <td colspan="4"><strong>Total</strong></td>
            <td class="amount"><strong>₹${total.toLocaleString('en-IN')}</strong></td>
          </tr>
        </tbody>
      </table>
      
      <p class="footer">
        Total expenses: ${expenses.length} | 
        Report generated by ExpenseTrack
      </p>
    </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }
}
